### ISSUE TITLE
dirs fails when there is no dirs

### ISSUE THREAD

**Issue by LoLei** [amirashabani/list#1]
Using the `dirs` argument with no present dirs in the current dir produces an arguably bad reading error.
```
$ ./list dirs
ls: cannot access '*/': No such file or directory
```
Maybe add a case for when there are no directories to produce a better output message?
Also, shouldn't it output at least the `.` and `..` dirs anyway?

**Comment by amishbni** [comment]
I agree with the first part of your issue, when there's no directories, it shouldn't output anything. [This commit](https://github.com/amirashabani/list/commit/10bd62c0473e3c342f6591df66e6de7bca395285) should fix that.

As for the second part, I intentionally removed those directories from output, because I don't think seeing them is very useful.
